### ISSUE TITLE
The color of the dashed border on the drop-zone should be updated when dragging a valid file.

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/file-uploader#24]
Got a brief message from Nicole about this.  The dashed border should change color when valid file is being dragged.  I suspect the color should be celestine to match the text color.  Nicole would be able to confirm.

**Comment by nicolebezaire** [comment]
Yep, it's Celestine.

**Comment by dlockhart** [comment]
Also, all the text is turning blue on-hover instead of just the border and icon. Will fix at the same time.
